Add base exception

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.kts\?$')
-DETEKT_TARGETS=$(echo "$CHANGED_FILES" | grep '\.kt$' | tr '\n' ',' | sed 's/,$//')
+KOTLIN_FILES=$(echo "$CHANGED_FILES" | grep '\.kt$')
 
 if [ -n "$CHANGED_FILES" ]; then
   echo "🔍 Found changed Kotlin files:"
@@ -20,15 +20,11 @@ if [ -n "$CHANGED_FILES" ]; then
     exit 1
   fi
 
-  if [ -n "$DETEKT_TARGETS" ]; then
-    echo "🔎 Running detekt on changed files..."
-    ./gradlew detekt --detekt-input "$DETEKT_TARGETS"
-    if [ $? -ne 0 ]; then
-      echo "❌ Detekt check failed! Please fix the issues and try again."
-      exit 1
-    fi
-  else
-    echo "ℹ️ No .kt files to check with Detekt."
+  echo "🔎 Running detekt..."
+  ./gradlew detekt
+  if [ $? -ne 0 ]; then
+    echo "❌ Detekt check failed! Please fix the issues and try again."
+    exit 1
   fi
 else
   echo "ℹ️ No changed Kotlin files to check."
