Improve pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -21,10 +21,12 @@ if [ -n "$CHANGED_FILES" ]; then
   fi
 
   echo "🔎 Running detekt..."
-  ./gradlew detekt || {
-    echo "❌ Detekt check failed! Please fix the issues and try again."
-    exit 1
-  }
+    ./gradlew detekt
+    DETEKT_EXIT_CODE=$?
+    if [ $DETEKT_EXIT_CODE -ne 0 ]; then
+      echo "❌ Detekt check failed! Please fix the issues and try again."
+      exit 1
+    fi
 else
   echo "ℹ️ No changed Kotlin files to check."
 fi
